version: 1.0
provider:
  name: openfaas
  gateway: http://209.38.112.33:8080
functions:
  auth-function:
    lang: dockerfile
    handler: ./auth-functions
    image: abdallah128/auth-routes:latest
    imagePullPolicy: Always
  user-function:
    lang: dockerfile
    handler: ./user-functions
    image: abdallah128/user-routes:latest
    imagePullPolicy: Always    
  post-function:
    lang: dockerfile
    handler: ./post-functions
    image: abdallah128/post-routes:latest
    imagePullPolicy: Always    
  frontend-function:
    lang: dockerfile
    handler: ./frontend-function
    image: abdallah128/frontend-function:latest
    imagePullPolicy: Always    
